Ajout de références perso (électronique, algo pathfinding, VS code, forum)
VRAC-team/la-maxi-liste-ressources-eurobot pull request #1
Opened 2020-05-15 17:09 UTC by Adri1G

C'est cool ce repot. ça donne un bon getting started :-)

2020-05-15 18:34 UTC, monowii requested changes
De bonnes références 😃, nécessites quelques modifs pour le merge

2020-05-15 18:34 UTC, monowii commented on README.md
> +[LIBRARY - PythonRobotics](https://atsushisakai.github.io/PythonRobotics/)
Les tags qui précèdent les ressources académiques sont en français, donc LIBRAIRIE.

Créer une sous catégorie 1.3.2 Intelligence Artificielle.
Ajouter la description pour PythonRobotics: "Python sample codes for robotics algorithms"

2020-05-15 18:34 UTC, monowii commented on README.md
> +
Ajouter nom de l'auteur et changer la description: Coder une IA - alexnesnes
Ajouter le github: https://github.com/nesnes/Eurobot-AI

2020-05-15 18:34 UTC, monowii commented on README.md
> +> * [Visual Studio Code](https://code.visualstudio.com/): rapide, modulaire, intégration de Arduino (compilation) [vidéo présentation Peronnin](https://www.youtube.com/watch?v=o2aD2kwinJM)
Cela devrait se trouver avec Arduino ci-dessus (et non STM32)

2020-05-15 18:34 UTC, monowii commented on README.md
> +[Robot de recherche Facebook](https://pyrobot.org/)
Description plus détaillé: "PyRobot - light weight, high-level interface which provides hardware independent APIs for robotic manipulation and navigation by facebook research."

2020-05-15 23:41 UTC, Adri1G commented
> 
> 
> De bonnes références smiley, nécessites quelques modifs pour le merge

Merci :-). C'est bon j'ai rectifié

2020-05-16 09:33 UTC, monowii requested changes
Tu devais être fatigué quand t'as fait cette modif 😬. La prochaine c'est la bonne!

2020-05-16 09:33 UTC, monowii commented on README.md
> +* [KiCad](https://kicad-pcb.org/): A Cross Platform and Open Source Electronics Design Automation Suite (Tutoriel)[https://www.youtube.com/watch?v=C9EWrKw9Qz8&list=PLuQznwVAhY2VoayfSraJjI-Yr2OSGmFKt]
Inversion de la syntax Markdown entre le [nom du lien] et (l'URL)

2020-05-16 09:33 UTC, monowii commented on README.md
> +[VIDEO - Coder une IA - alexnesnes](https://www.youtube.com/channel/UCg1vR097bAzmJzeMBWl7Zzw), (depot GitHub Eurobot-AI)[https://github.com/nesnes/Eurobot-AI]
Inversion de la syntax Markdown entre le [nom du lien] et (l'URL)

2020-05-16 15:23 UTC, merged